---
- hosts: terraform@ansible-ubuntu
  tasks:
  - name: Run apt.yml if OS is Ubuntu
    import_tasks: apt.yml
    when: ansible_distribution == "Ubuntu"
  - name: Run yum.yml if OS is CentOS
    import_tasks: yum.yml
    when: ansible_distribution == "CentOS"
...
